[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutator = "0.4.0"
itertools = "0.10"
pathfinding = "3.0.5"
scan_fmt = "0.2.6"
petgraph = "0.6.0"